### ISSUE TITLE
Mock Turtle repo misconfiguration

### ISSUE THREAD

**Issue by daniel-beck** [cider-security-research/cicd-goat#17]
Alice is able to merge her own PRs to `Wonderland/mock-turtle`.

No need to be clever with the diff when you can press Merge (which is pretty clearly not the intended approach).

At a glance, https://github.com/cider-security-research/cicd-goat/blob/fd2e42aa02c5729d9c9ddef284f25c6c08fc50ef/gitea/gitea.yaml#L94-L101 looks like it shouldn't be possible, but I was able to do it anyway.

**Comment by asi-cider** [comment]
Thanks again for the thorough review. I've added a parameter that was missing. I'll release it soon.
