### ISSUE TITLE
Hearts description is misleading

### ISSUE THREAD

**Issue by daniel-beck** [cider-security-research/cicd-goat#18]
Top-level credentials in Jenkins can have scope "Global" or "System". You use the latter for credentials for agents etc. that should not be made available to jobs. The description of "Hearts" states:

> These are System credentials stored on Jenkins!

For anyone aware of this distinction, this would be misleading. A pipeline would not have access to System scoped credentials.

**Comment by asi-cider** [comment]
Thanks Daniel. Hearts is not a pipeline, but a freestyle job. The purpose is to load the System creds (the flag) when running the job.
If we change "pipeline" to "job" in the description, would that address the issue in your opinion?

**Comment by daniel-beck** [comment]
@asi-cider The same applies to both freestyle jobs and pipelines. To see the effect of the option I am referring to and how it relates to Hearts, I recommend you boot up the environment and change the "Scope" property of the credential from "Global" to "System".

**Comment by asi-cider** [comment]
My mistake, I was sure that I configured it as systems credentials and that it worked with freestyle jobs. I rewrote the scenario, you can see it here: https://github.com/cider-security-research/cicd-goat/blob/bug-fixes/solutions/08-hearts.md

**Comment by daniel-beck** [comment]
@asi-cider Looks good, thanks! (Untested.)

If you want, you could even limit the user further to make the instance more resemble one where admins are aware of various weaknesses and restrict access (full control of all agents is a lot): Give knave just the permission to configure and connect a single pre-existing agent, that is currently configured to connect via Inbound Agent Protocol. The solution would be to change the agent launcher to SSH.
