### ISSUE TITLE
Impossible condition - task10

### ISSUE THREAD

**Issue by v3nd1g0** [cider-security-research/cicd-goat#25]
Hi, guys!

Amazing lab, thank you!

I have question about task 10, file Jenkinsfile, line 14. This condition ought to be true to merge my pull request in the main branch. But this condition can't be true because `$(wc -l <version)` always return 1 (1 string in the file) and it's can't be equal to 0.

Thank you in advance.

**Comment by omer-cider** [comment]
Hi @v3nd1g0, welcome and great to see you like to lab!
This shouldn't be a mistake, and it works for me. Have you tried running this command on this file and see what it returns?
Also, have you tried following the hints or solution and see if it works for you?

**Comment by 4d0n** [comment]
Hi @omer-cider. Thank you for your reply.
I have tested this expression in zshrc in such conditions:
- empty `version` file
```
$ > ./version
$ if [ $(wc -l <version) -eq 0 -a $(grep -Po "^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$" version) ] ; then check2=true; else check2=false; fi && echo $check2
false
```
- `version` file with 1.0.13 (grep pattern ok)
```
$ echo "1.0.13" > ./version 
$ if [ $(wc -l <version) -eq 0 -a $(grep -Po "^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$" version) ] ; then check2=true; else check2=false; fi && echo $check2
false
```
- `version` file with 100.1000.1000 (grep pattern no ok)
```
$ echo "1.100.100" > ./version 
$ if [ $(wc -l <version) -eq 0 -a $(grep -Po "^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$" version) ] ; then check2=true; else check2=false; fi && echo $check2
false
```
In each case I have reached check2 == false.

What am I missing?
Thank you in advance.

P.S. I have checked writeup, but it doesn't work for me :c

**Comment by v3nd1g0** [comment]
Hi @omer-cider. Thank you for your reply.
I have tested this expression in zshrc in such conditions:
- empty `version` file
```
$ > ./version
$ if [ $(wc -l <version) -eq 0 -a $(grep -Po "^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$" version) ] ; then check2=true; else check2=false; fi && echo $check2
false
```
- `version` file with 1.0.13 (grep pattern ok)
```
$ echo "1.0.13" > ./version 
$ if [ $(wc -l <version) -eq 0 -a $(grep -Po "^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$" version) ] ; then check2=true; else check2=false; fi && echo $check2
false
```
- `version` file with 100.1000.1000 (grep pattern no ok)
```
$ echo "1.100.100" > ./version 
$ if [ $(wc -l <version) -eq 0 -a $(grep -Po "^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$" version) ] ; then check2=true; else check2=false; fi && echo $check2
false
```
In each case I have reached check2 == false.

What am I missing?
Thank you in advance.

P.S. I have checked writeup, but it doesn't work for me :c

**Comment by omer-cider** [comment]
Hi @v3nd1g0, `wc -l <version` counts the number of newlines. If you'll make sure to remote any `\n`s from the _version_ file, the command will return _true_.

**Comment by v3nd1g0** [comment]
Thank you, you are right!
