### ISSUE TITLE
Download & Run section should be updated for newer implementations of docker compose

### ISSUE THREAD

**Issue by codevbus** [cider-security-research/cicd-goat#36]
Docker is moving towards a plugin model and away from `docker-compose`.

Newer invocations drop the hyphen: `docker compose`.

Additional context: https://docs.docker.com/compose/cli-command-compatibility/

Happy to submit a PR to update the documentation if that's appropriate.

**Comment by asi-cider** [comment]
Hey @codevbus,

Thanks for the suggestion! You're welcome to create a PR and modify the README and .circleci/config.yml file to make sure everything works in the ci and release jobs.

**Comment by codevbus** [comment]
Howdy @asi-cider! Apologies for the delay: #38

**Comment by nvwebd** [comment]
Hey.

Just wanted to ask when is this getting merged? Wanted to take the challenges for a spin.

I was referred here by John Hammonds Video on YT ( from 3 days ago ), so I would think it would be sweet if it gets updated.

Cheers.

**Comment by asi-cider** [comment]
> Hey.
> 
> Just wanted to ask when is this getting merged? Wanted to take the challenges for a spin.
> 
> I was referred here by John Hammonds Video on YT ( from 3 days ago ), so I would think it would be sweet if it gets updated.
> 
> Cheers.

Hey, the challenges are working regardless of this issue.
If are still some unresolved points regarding this issue, if you'd like to can contribute to resolve them
