### ISSUE TITLE
Docker Hub - Image Access Management restricts ability for organizations to run cicd-goat

### ISSUE THREAD

**Issue by abacchi** [cider-security-research/cicd-goat#41]
Paid subscriptions of Docker Hub for organizations allow for the restrictions of what repositories their members can interact with.

https://docs.docker.com/docker-hub/image-access-management/
With image access management turned on, community images are restricted [blocked] by default. This covers the cicd-goat images and disallows them from running the platform.

There does not seem to be a way for administrators to allow individual Docker Hub repositories in the image access management settings.

Some solutions off the top of my head don't sound great:

- Host the images somewhere else.
- Turn off image access management / allow community images.
- Become a Docker Verified Publisher Images organization - and the administrator of the organization would need to allow those.

**Comment by asi-cider** [comment]
Hey @abacchi,

Hosting the images in a different repository does not seem to have high demand.
Becoming a Docker Verified Publisher is not prioritized at the moment.
Please address this issue within your organization.

Thank you.
