### ISSUE TITLE
Jenkins builds crashing on Mac M1

### ISSUE THREAD

**Issue by tgdfool2** [cider-security-research/cicd-goat#51]
Hi All,

First of all, thanks a lot for this great project!

I tried to run some scenarios on my MacBook Pro (M1) and the Jenkins builds are failing with the following error:
![image](https://user-images.githubusercontent.com/66017789/227238737-0743c7ed-9105-46ff-8c9d-2dc33bf70ada.png)

Running on the latest Docker Desktop Release:
![image](https://user-images.githubusercontent.com/66017789/227239038-4801768b-ff0b-4740-a177-d0348784a951.png)

Am I the only one facing this issue?

**Comment by asi-cider** [comment]
> I was able to fix the issue by rebuilding the `jenkins-agent` container image locally. Had to tweak it a bit to install `terraform` from binary instead of from source, see #52.

Thank you for reporting this issue!
I'll add to #52 building of native arm64 image for the Jenkins agent so people won't have to rebuild locally

**Comment by asi-cider** [comment]
> > I was able to fix the issue by rebuilding the `jenkins-agent` container image locally. Had to tweak it a bit to install `terraform` from binary instead of from source, see #52.
> 
> Thank you for reporting this issue! I'll add to #52 building of native arm64 image for the Jenkins agent so people won't have to rebuild locally

Hey, @tgdfool2 I created a new release. Please try to pull the new docker images and let me know if it works.

**Comment by tgdfool2** [comment]
Hi @asi-cider. Thanks a lot for the new release. Looks much better now ;-)

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/66017789/227447689-ef450273-a939-4c23-be17-f7dfd1bad8e9.png">

Going to continue the challenges and report in case of issues.
