### ISSUE TITLE
Align each challenge with cider-security-research/top-10-cicd-security-risks

### ISSUE THREAD

**Issue by huornlmj** [cider-security-research/cicd-goat#57]
From a learning perspective, I believe that it would be beneficial if each challenge could in some way be mapped to one or more of the Cider Top 10 CICD security risks at https://github.com/cider-security-research/top-10-cicd-security-risks.  That way, pen testers / DevSecOps can more easily explain to DevOps why certain security measures should be taken as they will have a 'this is what could happen' link from each top 10, and a reverse 'this is what you should do to avoid' link from each challenge.

I'm going to map them myself for my own mentoring but sharing the suggestion here too.

**Comment by asi-cider** [comment]
Hey, we have this mapping in each of the solutions at the top of the page. You're welcome to suggest additions.
