### ISSUE TITLE
Task Gryphon pipelines does not run by gryphon user

### ISSUE THREAD

**Issue by kairat1115** [cider-security-research/cicd-goat#58]
I do not know if it's intended, `gryphon` user has developer permissions and cannot run pipelines for `wonderland/awesome-app` and `wonderland/nest-of-gold`.
![image](https://github.com/cider-security-research/cicd-goat/assets/22301117/6d69ece7-44a0-4f34-9fa8-e02f6a3aa8aa)

I have logged in as root and bumped permission to maintainer for `gryphon` user and then pipelines were able to run 10 minutes.

I have also checked solution in https://github.com/cider-security-research/cicd-goat/blob/main/solutions/gryphon.md and guess pipelines worked there at the time of writing.

**Comment by asi-cider** [comment]
Hey, the pipelines should run periodically by a different user as a result of schedule configuration. 
Please let me know if they don't
