### ISSUE TITLE
Provide a build option for loopback for security purposes

### ISSUE THREAD

**Issue by huornlmj** [cider-security-research/cicd-goat#65]
The current deployment exposes all of the services to the host network.  For added security and for those who do not want to have these exposed this way and to only have them exposed locally, please provide an option for loopback binding only.

**Comment by asi-cider** [comment]
Could you please create a PR to offer a solution?

**Comment by huornlmj** [comment]
Sorry I don't have a PR - this is just a security recommendation / feature request.  I don't know what would need to change in order for all the sockets to only be bound to the hosts' loopback interface.
