### ISSUE TITLE
Creating new users

### ISSUE THREAD

**Issue by fabiox77** [cider-security-research/cicd-goat#68]
Hi,
first of all thanks for this very cool project!

I tried it locally and I could only see the pre-created accounts and when I tried, for instance, to create a new `Jenkins` users I noticed it was not possible.

If i wanted to use it but allowing the users to register and try the challenges independently without seeing what the other user have done what should I need to need?

My final goal is to try this project but with multiple people/team registered. Maybe via ctfd would be easier?

Thanks

**Comment by asi-cider** [comment]
Can you elaborate more and attach screenshots? have you used the admin users from the [break-glass.md](https://github.com/cider-security-research/cicd-goat/blob/main/break-glass.md) file?
CTFd does allow for multiple users.
