### ISSUE TITLE
Why FLAG6 in Twiddledum?

### ISSUE THREAD

**Issue by huornlmj** [cider-security-research/cicd-goat#77]
https://github.com/cider-security-research/cicd-goat/blob/00edb3efe0397c7ca3185b6933f0573d43d50b53/solutions/twiddledum.md?plain=1#L15

FLAG6 is selected as the flag with no obvious rationale.  Why FLAG6?

**Comment by huornlmj** [comment]
(－‸ლ)   of course.

**Comment by TheCipherCat** [comment]
There's another way you could've figured it out without looking at the challenge details. I'm not a developer or anything, but I've seen how other people do it. When you edit the `index.js` file, you can add the following line to find the environment variables:

`console.log(process.env);`

Add the new release and rebuild manually from Jenkins. It will print the environment variables. One of which is `FLAG6: ****` which can lead you to the next step. =)
