### ISSUE TITLE
gitea/repositories/mock-turtle/Jenkinsfile broken stipulation

### ISSUE THREAD

**Issue by SS4ar** [cider-security-research/cicd-goat#85]
hi, i think here a contradictory terms `if [ $(wc -l <version) -eq 0 -a $(grep -Po "^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$" version) ] ; then check2=true; else check2=false; fi`
we must make file with 0 strings and with number

**Comment by Oakleysecurity** [comment]
> 嗨，我认为这里有一个矛盾的术语，`if [ $(wc -l <version) -eq 0 -a $(grep -Po "^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$" version) ] ; then check2=true; else check2=false; fi` 我们必须用 0 个字符串和数字制作文件
I also encountered the same problem.

**Comment by Oakleysecurity** [comment]
> hi, i think here a contradictory terms `if [ $(wc -l <version) -eq 0 -a $(grep -Po "^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$" version) ] ; then check2=true; else check2=false; fi` we must make file with 0 strings and with number

I also encountered the same problem

**Comment by Cloud-Snow** [comment]
this has been solved in a clossed issue #25 
actually, the command `wc -l < version ` checks the number of `\n`
so Just make sure there is no `\n` in the file

**Comment by vdespa** [comment]
For me, this worked without any issues. I think it can be closed.

**Comment by TupleType** [comment]
Thank you
